### ISSUE TITLE
Tasks List for Exploration & Path Diversity

### ISSUE THREAD

**Issue by jJasonWang** [berkeley-stat222/mousestyles#122]
Currently working on:
- [x] Revise the path.rst (change the purpose of the project and add exploration plot)
- [x] function that outputs path start indices and end indices
- [x] function that filters out the paths based on time spending on the paths  
- [x] function that calculates the length and average speed of a path
- [x] function that calculates the acceleration during paths
- [x] function that removes duplicated rows.
- [x] plot function that visualizes the path
- [x] Setup package for path project (folder structure) and import the function from `__init__.py`

I created the above tasks list. Please check @alannaiverson, @aksam-ahmad, @jcpalumbo3, @sicihuang , @togawa28. Feel free to add anything I missed.

If you have good suggestions for the path project, feel free to add it below!!!

**Comment by togawa28** [comment]
- [ ] write a function to remove duplicated rows.

Since we don't want to see some duplicated rows (i.e. same x,y-coordinates with different timestamps) in movement objects, I think we need to write a function to remove those rows. It seems to be a very trivial problem as we see only at most 10 such rows in one movement, but if we leave them, `compute_angles` function returns `NaN` for such rows because the length of the vector between such rows is 0. I'm currently writing this function, and I just want to add this to Jason's list.

**Comment by togawa28** [comment]
- [ ]  plot function that visualizes the path

@jJasonWang, what function do you intend in this check box? What @alannaiverson made is what you need? Or do you mean the function to visualize a path (or several paths) in an original form as followings?
![example_plot_one_path](https://cloud.githubusercontent.com/assets/14063064/15102696/4d29a68e-1557-11e6-9711-b462e718395f.png)
![example_plot_several_paths](https://cloud.githubusercontent.com/assets/14063064/15102699/51612dbc-1557-11e6-8f01-2dc0b6ecf38b.png)

**Comment by jJasonWang** [comment]
Yeah, it is the function create the plot like you show above. Should we wrap it into a function? Originally, I think it might be great if we can add some rectangle to illustrate the area for home, water, and food. However, it may not be necessary.

**Comment by togawa28** [comment]
I've already written a draft of such function and need it discussed and reviewed by someone, so I can create another pull request. Could we move to the pull request and keep discussing some additional functionalities such as what you just suggested?

**Comment by jJasonWang** [comment]
Sure, I can review the pull request and see what functionality will be good!

**Comment by togawa28** [comment]
I've started formalizing the functions for advanced features and writing those test functions. The newly added features are:
1. area of the rectangle spanned by path
2. radius and center angles in path
3. area covered by path
4. distance between the start and end points in path
Since the amount of necessary works is overwhelming my capacity (especially in writing test functions,) I don't think I can finish to push test functions by Thursday. Could anyone help me in building test functions? 
I'll make a pull request for the main functions soon, but you can find that these functions look like a nightmare and even reviewing all through is a pretty heavy work: I'm a bit skeptical that it's possible to finish them by the end of this week...
