### ISSUE TITLE
Overview of Project 4: Ultradian Analyses

### ISSUE THREAD

**Issue by boyinggong** [berkeley-stat222/mousestyles#6]
- Daily cycle
- Grouped by species (strains) or other basic characteristics of mouses
- [ ] What basic characteristics do we have? 
- Variables of interest: AS/IS, Drinking/Feeding/Locomotion

**Comment by pigriver123** [comment]
Figure out what is in Active State and what is in Inactive State

**Comment by pigriver123** [comment]
Figure out what is the different of the daily pattern among different strains

**Comment by pigriver123** [comment]
Figure out what are the difference of the daily pattern among different strains

**Comment by jarrodmillman** [comment]
For Monday, your task is to produce a 1 page summary here:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/problem/ultradian.md

Your goal is to understand the problem. You are welcome to look at the code, but you shouldn't be working with code at this point. You also probably don't want to focus on the algorithms yet either.

If this isn't clear, please reread the project assignment:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/assignment/mouse.pdf

Feel free to discuss the issue on Piazza.

**Comment by peterasujan** [comment]
Comments from class:
- Think about known/expected cycles - time to digest, IS/AS cycle, etc.
- Investigate cycles longer than 24 hours
- Do cycles differ during the acclimatization period?
- Think about possible hypothesis tests (what is an appropriate null model?)

**Comment by jcyhong** [comment]
To ensure consistency among the descriptions/overview of the subprojects, there should be the following six sections:
-Introduction
-Fundamental Questions
-Exploratory Questions
-Preliminary Tasks
-Additional Remarks
-References

The introduction section should include some background of the problem and one/two-sentences summarizing the objective of the subproject.
The fundamental questions section should highlight the fundamental questions we would like the subproject to address. State the main hypotheses, if any.
The exploratory questions section should identify questions that serve as the starting point of the subproject. The part is somewhat more open-ended relative to the key questions section.
The preliminary tasks section should identify what data processing/additional work is needed before we start our data analysis.
The additional remarks section should include any comments/ideas not addressed in the previous sections, such as what additional data/explanation of the data might help the analysis.
The reference section should include all the sources used when writing up the problem statements. Try not to cite wikipedia, as many researchers do not view it as a credible source.

To avoid redundancy, remove any data description section. We will include the data description section in the overview. If you are sure that the subproject should focus on only a subset of the variables/data, rather than the entire dataset, mention that as an additional remark.
