### ISSUE TITLE
Overview of Project 2: Exploration & Path Diversity

### ISSUE THREAD

**Issue by changsiyao** [berkeley-stat222/mousestyles#7]
**Exploration & Path Diversity**

What's the different moving patterns for each mouse strain?

**Comment by jarrodmillman** [comment]
For Monday, your task is to produce a 1 page summary here:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/problem/path.md

Your goal is to understand the problem. You are welcome to look at the code, but you shouldn't be working with code at this point. You also probably don't want to focus on the algorithms yet either.

If this isn't clear, please reread the project assignment:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/assignment/mouse.pdf

Feel free to discuss the issue on Piazza.

**Comment by changsiyao** [comment]
@pttzty @MengfeiJiang

**Comment by peterasujan** [comment]
Comments from class:
- We'll need to chunk the observations into a grid. What would be an appropriate grid size (the authors use 1cm)?
  - First, we need to decide what our goal is. One example is classification, which gives us an obvious measure of goodness (i.e. accuracy).
  - Can plot and decide if things look too chunky or too jittery.
  - Can see if temporal patterns emerge.
- Other considerations:
  - anomaly detection
  - may be able to detect different types of events using different grid sizes
  - directed actions vs. noisier actions
  - extract "vectors" of movement, which can include a similarity metric for different paths

**Comment by jcyhong** [comment]
To ensure consistency among the descriptions/overview of the subprojects, there should be the following six sections:
-Introduction
-Fundamental Questions
-Exploratory Questions
-Preliminary Tasks
-Additional Remarks
-References

The introduction section should include some background of the problem and one/two-sentences summarizing the objective of the subproject.
The fundamental questions section should highlight the fundamental questions we would like the subproject to address. State the main hypotheses, if any.
The exploratory questions section should identify questions that serve as the starting point of the subproject. The part is somewhat more open-ended relative to the key questions section.
The preliminary tasks section should identify what data processing/additional work is needed before we start our data analysis.
The additional remarks section should include any comments/ideas not addressed in the previous sections, such as what additional data/explanation of the data might help the analysis.
The reference section should include all the sources used when writing up the problem statements. Try not to cite wikipedia, as many researchers do not view it as a credible source.

To avoid redundancy, remove any data description section. We will include the data description section in the overview. If you are sure that the subproject should focus on only a subset of the variables/data, rather than the entire dataset, mention that as an additional remark.
