### ISSUE TITLE
Overview of Project 1: Behavior Model

### ISSUE THREAD

**Issue by CenzhuoYao** [berkeley-stat222/mousestyles#8]
## Todo List
- [x] Add in description of AS and IS
- [x] Include slides from Chris

###  Assignment
For Monday, your task is to produce a 1 page summary here:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/problem/behavior.md

Your goal is to understand the problem.  You are welcome to look at the code, but you shouldn't be working with code at this point.  You also probably don't want to focus on the algorithms yet either.

If this isn't clear, please reread the project assignment:
https://github.com/berkeley-stat222/mousestyles/blob/master/doc/assignment/mouse.pdf

Feel free to discuss the issue on Piazza.
### Comments
- How do we define active and inactive state? Make sure the data is sensible (might want to make a few plots).
- See other paper describing home cage monitoring system (mentioned in assignment pdf).
- Might be useful to include some sketches, or the slides from Chris.

**Comment by z357412526** [comment]
@jarrodmillman @jcyhong It is saying that I do not have writing access when I try to merge something in my team. Attached is the screenshot. Could you please take a look at that?


<img width="850" alt="screen shot 2016-04-03 at 2 22 15 pm" src="https://cloud.githubusercontent.com/assets/14003168/14235037/bc206512-f9a7-11e5-8bf2-964f7507bc79.png">

**Comment by jarrodmillman** [comment]
If you can come to class 5min early on Monday, I can help you with this.  I will want you to rebase on master first.  If you aren't sure how to do that, I can quickly walk you through it before class starts.

**Comment by peterasujan** [comment]
Comments from class:
- How do we define active and inactive state? Make sure the data is sensible (might want to make a few plots).
- See other paper describing home cage monitoring system (mentioned in assignment pdf).

**Comment by jcyhong** [comment]
To ensure consistency among the descriptions/overview of the subprojects, there should be the following six sections:
-Introduction
-Fundamental Questions
-Exploratory Questions
-Preliminary Tasks
-Additional Remarks
-References

The introduction section should include some background of the problem and one/two-sentences summarizing the objective of the subproject.
The fundamental questions section should highlight the fundamental questions we would like the subproject to address. State the main hypotheses, if any.
The exploratory questions section should identify questions that serve as the starting point of the subproject. The part is somewhat more open-ended relative to the key questions section.
The preliminary tasks section should identify what data processing/additional work is needed before we start our data analysis.
The additional remarks section should include any comments/ideas not addressed in the previous sections, such as what additional data/explanation of the data might help the analysis.
The reference section should include all the sources used when writing up the problem statements. Try not to cite wikipedia, as many researchers do not view it as a credible source.

To avoid redundancy, remove any data description section. We will include the data description section in the overview. If you are sure that the subproject should focus on only a subset of the variables/data, rather than the entire dataset, mention that as an additional remark.
