### ISSUE TITLE
Consider combining Projects 1 and 3

### ISSUE THREAD

**Issue by peterasujan** [berkeley-stat222/mousestyles#85]
This is (probably) a good idea, but let's delay actually making the change until after we've run it by the Tecott lab.  There may be something we are missing that would make us change our mind.

**Comment by shamindras** [comment]
@peterasujan - I agree that we should wait until after Monday. After reading through the key question I have for the project 3 team is whether IS/ AS is **given** or whether it is to be **predicted**?

In project 1 we are definitely assumed that IS/ AS are rule based classification from observational data that are provided and **not** predicted as we can see from the data

Project 3 seems to want to **predict** IS/ AS in the HMM. I think the reason for this should be made clear given that we have IS/ AS given to us. It could be a great thing to do. I am just not sure at the moment why this is the case. @wyshi, @lynnzhao @mingyungkim is it possible to make edits to the document to clarify your reasons?

**Comment by dylandaniels** [comment]
I don't think that "predicting" AS/IS makes much sense. These are terms with fairly strict definitions--a mouse is in AS when it's moving/drinking/feeding, and is in IS otherwise. Unless by predicting, you're talking about a time-series model whereby we predict when a transition from AS --> IS or IS --> AS occurs, it's an inappropriate use of an HMM.

I think the discussion we had in class on Wednesday where we proposed predicting unobservables such as "hungry," "tired," etc. would be much more fruitful. We should be sure to ask the Tecott Lab tomorrow whether they think that's an interesting and worthwhile endeavor.

**Comment by lynnzhao92** [comment]
@shamindras @dylandaniels @peterasujan Thank you for reminding us this issue. We will definitely ask the Tecott Lab during Tomorrow's discussion. We should figure out the purpose/expectation of this subproject "Dynamics of AS/IS" first and then go further to the actual analysis. Thank you for all the advices.
